---

# iptables -t nat -A PREROUTING -i eth0 -p tcp --dport $srcPortNumber -j REDIRECT --to-port $dstPortNumber
# iptables -t nat -L -n -v

- name: Redirecting IPTables port
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: enp0s3
    protocol: tcp
    # match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: "{{ dest_http }}"
    comment: "Redirect web traffic to port {{ dest_http }}"

- name: Redirecting IPTables port
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: enp0s3
    protocol: tcp
    # match: tcp
    destination_port: 443
    jump: REDIRECT
    to_ports: "{{ dest_https }}"
    comment: "Redirect web traffic to port {{ dest_https }}"
