# Purpose: Handlers for homelab role
# Last Updated: 2018.06.11
# Notes:
---

- block:

    - name: "Start NTP Service"
      service:
       name: "{{ ntp_service }}"
       state: started
       enabled: yes

    - name: "Restart NTP Service"
      service:
       name: "{{ ntp_service }}"
       state: restarted

  become: true