# Purpose:
# Notes:
---


dependencies: []

galaxy_info:
  author: drewgwallace
  description: Skel.
  company: 
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - default